const Constants = {};

Constants.USER_CONNECTED = "USER_CONNECTED";
Constants.CREATE_ROOM = "CREATE_ROOM";
Constants.JOIN_ROOM = "JOIN_ROOM";
Constants.LEAVE_ROOM = "LEAVE_ROOM";
Constants.GET_GAME = "GET_GAME";
Constants.GET_GAME_DATA = "GET_GAME_DATA";
Constants.ASK_DATA = "ASK_DATA";
Constants.USER_CONNECTED = "USER_CONNECTED";
Constants.ROOM_CREATED = "ROOM_CREATED";
Constants.CHANGE_STATUS = "CHANGE_STATUS";
Constants.SEND_SCORE = "SEND_SCORE";
Constants.RESET_GAME = "RESET_GAME";
Constants.RESET_GAME_ALL = "RESET_GAME_ALL";
Constants.UPDATE_QUESTIONS = "UPDATE_QUESTIONS";
Constants.DEFAULT_QUESTIONS = "DEFAULT_QUESTIONS";
Constants.USER_FINISHED = "USER_FINISHED";
Constants.RESET_ALL_INSTANCES = "RESET_ALL_INSTANCES";
Constants.RESET_ALL_INSTANCES_REDIRECT = "RESET_ALL_INSTANCES_REDIRECT";
Constants.GET_USERS = "GET_USERS";
Constants.GET_USERS_DATA = "GET_USERS_DATA";

Constants.ERROR = "ERROR";

module.exports = Constants;
